remote_theme: pmarsceill/just-the-docs
logo: "/formival.png"

aux_links:
  "Formival on GitHub":
    - "//github.com/formival/formival"

footer_content: "Copyright &copy; 2020 Darren Mothersele. Distributed by an <a href=\"https://github.com/formival/formival/blob/master/LICENSE\">MIT license.</a>"
